### ISSUE TITLE
Problem with intel oneapi fortran compiler and aggressive optimization

### ISSUE THREAD

**Issue by filippolipparini** [ACoM-Computational-Mathematics/ddX#41]
Using -O3 -xHost flags with the intel OneAPI fortran compiler version 2021.3.0 produces buggy unstable code, unless the -fp-model=precise flag is added.
Also, we should get rid of gjinv.

**Comment by benjaminstamm** [comment]
Create item "Known issues" on Github-pages.
Add warning that we're adding -fp-model=precise for Intel compilers.
