### ISSUE TITLE
Cannot build ddX as CMake subproject

### ISSUE THREAD

**Issue by awvwgk** [ACoM-Computational-Mathematics/ddX#52]
Since `CMAKE_SOURCE_DIR` / `CMAKE_BINARY_DIR` are referenced it is currently not possible to include ddX as part of a superproject build. Preferably ddX could make use of `PROJECT_SOURCE_DIR` and `PROJECT_BINARY_DIR` to refer to source and build directories relative to the project root.

**Comment by Muxas** [comment]
resolved in #60
