### ISSUE TITLE
Unportable real kind declared

### ISSUE THREAD

**Issue by awvwgk** [ACoM-Computational-Mathematics/ddX#59]
The kind parameter for real values is currently declared as `kind=8`, which is not portable and fails with compiler like NAG Fortran. Preferably a kind parameter is declared using `selected_real_kind`.

For details on kind parameters in Fortran there is a good blog post at https://stevelionel.com/drfortran/2017/03/27/doctor-fortran-in-it-takes-all-kinds/.

**Comment by Muxas** [comment]
As can be seen at https://github.com/ACoM-Computational-Mathematics/ddX/blob/2b1260ed8ece9c20b3f10910bf024cbdeb12987e/src/ddx_definitions.f90#L19 we actually try to avoid `kind=8` declarations and use predefined compile-time constant with proper kind of double precision. It is still possible we missed something.

**Comment by awvwgk** [comment]
Sorry I was confused by the first file I opened `src/pcm_fmm.f90`. But after a closer look this isn't even part of the build.
